# Generated by Django 5.2.12 on 2026-07-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_certification_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationbackground',
            name='score_type',
            field=models.CharField(choices=[('Percentage', 'Percentage'), ('CGPA', 'CGPA'), ('Rank', 'Rank')], default='Percentage', max_length=15),
        ),
    ]
