# Generated by Django 5.2.12 on 2026-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_educationbackground_score_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationbackground',
            name='score',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
