# Generated by Django 5.2.12 on 2026-07-08 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_academiccalendar_target_section_and_more'),
        ('students', '0007_certification_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioncourse',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_institution_courses', to='students.studentprofile'),
        ),
        migrations.CreateModel(
            name='CourseLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='faculty.institutioncourse')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
