# Generated by Django 5.2.12 on 2026-07-08 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_section'),
        ('faculty', '0009_institutioncourse_enrolled_students_courselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutioncourse',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_courses', to='academics.department'),
        ),
    ]
