# Generated by Django 5.2.12 on 2026-07-09 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0010_institutioncourse_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorassignment',
            name='mentor',
            field=models.ForeignKey(limit_choices_to=models.Q(('role__in', ['Faculty', 'Mentor'])), on_delete=django.db.models.deletion.CASCADE, related_name='mentored_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentmentorassignment',
            name='mentor',
            field=models.ForeignKey(limit_choices_to=models.Q(('role__in', ['Faculty', 'Mentor'])), on_delete=django.db.models.deletion.CASCADE, related_name='student_mentor_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
